// Static job postings registry for the Careers section.
// Swap for a real data source (Supabase, ATS API, etc.) once the job listing design is approved.

const COMPANY = "Support Studio Technologies";

export const jobs = [
    {
        slug: "senior-product-designer",
        title: "Senior Product Designer",
        company: COMPANY,
        location: "San Francisco, CA",
        modeOfWork: "Hybrid",
        typeOfWork: "Full-time",
        experienceLevel: "Mid-Senior level",
        applicants: 47,
        postedAgo: "2 days ago",
        categories: [],
        aboutJob:
            "We're looking for a talented Senior Product Designer to join our growing team. You'll work closely with product managers, engineers, and other designers to create beautiful, intuitive user experiences that delight our customers. In this role, you'll have the opportunity to shape the future of our product and make a significant impact on millions of users worldwide.",
        responsibilities: [
            "Lead design projects from concept to completion",
            "Create wireframes, prototypes, and high-fidelity mockups",
            "Collaborate with cross-functional teams to define product requirements",
            "Conduct user research and usability testing",
            "Maintain and evolve our design system",
            "Mentor junior designers and contribute to design culture",
        ],
        qualifications: [
            "5+ years of experience in product design",
            "Strong portfolio demonstrating user-centered design solutions",
            "Proficiency in Figma, Sketch, or similar design tools",
            "Experience with design systems and component libraries",
            "Excellent communication and presentation skills",
            "Bachelor's degree in Design, HCI, or related field (or equivalent experience)",
        ],
    },
    {
        slug: "ai-data-engineer",
        title: "AI Data Engineer",
        company: COMPANY,
        location: "Chennai, India",
        modeOfWork: "On-site",
        typeOfWork: "Full-time",
        experienceLevel: "5-10 years",
        applicants: 32,
        postedAgo: "4 days ago",
        categories: ["Artificial Intelligence (AI) & Data"],
        aboutJob:
            "We're seeking an AI Data Engineer to design and maintain the data pipelines that power our clients' AI and analytics platforms. You'll work with large-scale enterprise datasets, build robust ETL workflows, and partner with data scientists to get models into production reliably.",
        responsibilities: [
            "Design, build, and maintain scalable data pipelines and ETL workflows",
            "Partner with data scientists to productionize machine learning models",
            "Optimize data storage and query performance across cloud platforms",
            "Implement data quality checks and monitoring",
            "Document data architecture and pipeline design decisions",
            "Mentor junior engineers on data engineering best practices",
        ],
        qualifications: [
            "5-10 years of experience in data engineering",
            "Strong proficiency in Python and SQL",
            "Experience with cloud data platforms (AWS, Azure, or GCP)",
            "Familiarity with orchestration tools such as Airflow or Dagster",
            "Understanding of data warehousing and modeling concepts",
            "Bachelor's degree in Computer Science, Engineering, or related field",
        ],
    },
    {
        slug: "machine-learning-analyst",
        title: "Machine Learning Analyst",
        company: COMPANY,
        location: "Chennai, India",
        modeOfWork: "On-site",
        typeOfWork: "Full-time",
        experienceLevel: "3-6 years",
        applicants: 21,
        postedAgo: "1 week ago",
        categories: ["Machine Learning (ML) & Analytics"],
        aboutJob:
            "As a Machine Learning Analyst, you'll help translate business problems into data-driven solutions. You'll build and evaluate models, analyze results, and communicate insights to stakeholders across our enterprise clients.",
        responsibilities: [
            "Build, train, and evaluate machine learning models for client use cases",
            "Analyze large datasets to identify trends and actionable insights",
            "Collaborate with engineering teams to deploy models into production",
            "Prepare clear reports and presentations for technical and non-technical stakeholders",
            "Stay current with advances in machine learning techniques and tooling",
            "Support experimentation and A/B testing for model improvements",
        ],
        qualifications: [
            "3-6 years of experience in a machine learning or data analysis role",
            "Strong knowledge of Python and common ML libraries (scikit-learn, PyTorch, etc.)",
            "Solid understanding of statistics and model evaluation techniques",
            "Experience working with SQL and large datasets",
            "Strong analytical and communication skills",
            "Bachelor's or Master's degree in a quantitative field",
        ],
    },
    {
        slug: "data-platform-specialist",
        title: "Data Platform Specialist",
        company: COMPANY,
        location: "Chennai, India",
        modeOfWork: "Hybrid",
        typeOfWork: "Full-time",
        experienceLevel: "5-10 years",
        applicants: 18,
        postedAgo: "1 week ago",
        categories: ["Cloud Computing & Services"],
        aboutJob:
            "We're looking for a Data Platform Specialist to help design and operate the enterprise data platforms that underpin our clients' analytics and AI initiatives. You'll work across infrastructure, governance, and platform reliability.",
        responsibilities: [
            "Administer and scale enterprise data platform infrastructure",
            "Implement data governance and access control policies",
            "Monitor platform health and resolve performance bottlenecks",
            "Support integration of new data sources and tools onto the platform",
            "Collaborate with security teams to ensure compliance requirements are met",
            "Provide platform documentation and onboarding support for engineering teams",
        ],
        qualifications: [
            "5-10 years of experience in data platform engineering or administration",
            "Experience with modern data platforms (Snowflake, Databricks, or similar)",
            "Familiarity with data governance and compliance frameworks",
            "Strong scripting skills (Python, Bash, or similar)",
            "Excellent problem-solving and cross-team collaboration skills",
            "Bachelor's degree in Computer Science, Engineering, or related field",
        ],
    },
    {
        slug: "artificial-intelligence-data",
        title: "Artificial Intelligence (AI) & Data",
        company: COMPANY,
        location: "Chennai, India",
        modeOfWork: "On-site",
        typeOfWork: "Full-time",
        experienceLevel: "5-10 years",
        applicants: 41,
        postedAgo: "3 days ago",
        categories: ["Artificial Intelligence (AI) & Data"],
        aboutJob:
            "We're growing our AI & Data practice and are looking for engineers who can design intelligent systems end-to-end, from data pipelines to production-ready AI models for enterprise clients.",
        responsibilities: [
            "Design and build AI-driven solutions for enterprise data platforms",
            "Partner with clients to translate business problems into data and AI use cases",
            "Own model development, evaluation, and deployment lifecycle",
            "Collaborate with data engineering teams on scalable pipelines",
            "Document architecture decisions and model performance",
            "Stay current with emerging AI tooling and best practices",
        ],
        qualifications: [
            "5-10 years of experience in AI/ML or data engineering roles",
            "Strong proficiency in Python and modern ML frameworks",
            "Experience with cloud AI platforms (AWS, Azure, or GCP)",
            "Solid understanding of data modeling and pipeline design",
            "Excellent communication and client-facing skills",
            "Bachelor's or Master's degree in Computer Science or related field",
        ],
    },
    {
        slug: "data-science-engineering",
        title: "Data Science & Engineering",
        company: COMPANY,
        location: "Bangalore, India",
        modeOfWork: "On-site",
        typeOfWork: "Full-time",
        experienceLevel: "3-6 years",
        applicants: 29,
        postedAgo: "5 days ago",
        categories: ["Artificial Intelligence (AI) & Data"],
        aboutJob:
            "We're hiring a Data Science & Engineering specialist to build the analytical foundations and predictive models that power decision-making for our enterprise clients.",
        responsibilities: [
            "Build and maintain data pipelines feeding analytics and ML workloads",
            "Develop statistical and machine learning models to answer business questions",
            "Partner with engineering to productionize data science outputs",
            "Perform exploratory data analysis to uncover trends and opportunities",
            "Present findings clearly to technical and non-technical stakeholders",
            "Contribute to internal data science tooling and standards",
        ],
        qualifications: [
            "3-6 years of experience in data science or data engineering",
            "Strong SQL and Python skills",
            "Experience with data warehousing and ETL tools",
            "Working knowledge of statistical modeling and experimentation",
            "Strong analytical and communication skills",
            "Bachelor's degree in a quantitative or engineering field",
        ],
    },
    {
        slug: "big-data-cloud-computing",
        title: "Big Data & Cloud Computing",
        company: COMPANY,
        location: "Hyderabad, India",
        modeOfWork: "Remote",
        typeOfWork: "Full-time",
        experienceLevel: "4-8 years",
        applicants: 24,
        postedAgo: "6 days ago",
        categories: ["Cloud Computing & Services"],
        aboutJob:
            "We're looking for a Big Data & Cloud Computing engineer to architect and scale the distributed data infrastructure behind our clients' cloud platforms.",
        responsibilities: [
            "Design and operate large-scale distributed data processing systems",
            "Build cloud-native data infrastructure across AWS, Azure, or GCP",
            "Optimize storage, compute, and cost efficiency of big data workloads",
            "Implement monitoring and reliability practices for data platforms",
            "Collaborate with security teams on cloud governance and compliance",
            "Mentor engineers on cloud and big data best practices",
        ],
        qualifications: [
            "4-8 years of experience in big data or cloud infrastructure engineering",
            "Hands-on experience with Spark, Kafka, or similar big data tools",
            "Strong knowledge of at least one major cloud provider",
            "Experience with infrastructure-as-code (Terraform, CloudFormation, etc.)",
            "Solid understanding of distributed systems fundamentals",
            "Bachelor's degree in Computer Science, Engineering, or related field",
        ],
    },
    {
        slug: "business-intelligence-visualization",
        title: "Business Intelligence & Visualization",
        company: COMPANY,
        location: "Pune, India",
        modeOfWork: "On-site",
        typeOfWork: "Contract",
        experienceLevel: "1-3 years",
        applicants: 16,
        postedAgo: "2 days ago",
        categories: ["Machine Learning (ML) & Analytics"],
        aboutJob:
            "We're looking for a Business Intelligence & Visualization specialist to turn complex enterprise data into clear, actionable dashboards and reports for our clients.",
        responsibilities: [
            "Design and build interactive dashboards and reports for business stakeholders",
            "Translate business requirements into data models and visualizations",
            "Maintain and optimize BI data sources and semantic layers",
            "Partner with analytics and engineering teams to ensure data accuracy",
            "Train business users on self-service BI tools",
            "Continuously improve reporting standards and visualization guidelines",
        ],
        qualifications: [
            "1-3 years of experience in business intelligence or data visualization",
            "Proficiency with BI tools such as Power BI, Tableau, or similar",
            "Strong SQL skills and understanding of data modeling",
            "Good eye for design and data storytelling",
            "Strong communication and stakeholder management skills",
            "Bachelor's degree in a related field or equivalent experience",
        ],
    },
    {
        slug: "cybersecurity-data-protection",
        title: "Cybersecurity & Data Protection",
        company: COMPANY,
        location: "Delhi, India",
        modeOfWork: "On-site",
        typeOfWork: "Full-time",
        experienceLevel: "6-10 years",
        applicants: 22,
        postedAgo: "1 week ago",
        categories: ["Cybersecurity & Risk Management"],
        aboutJob:
            "We're seeking a Cybersecurity & Data Protection specialist to safeguard enterprise systems and client data across our platforms, ensuring compliance with evolving security standards.",
        responsibilities: [
            "Design and implement security controls across cloud and on-prem systems",
            "Lead vulnerability assessments and penetration testing initiatives",
            "Develop and enforce data protection and access control policies",
            "Respond to and investigate security incidents",
            "Ensure compliance with relevant regulatory and industry standards",
            "Educate engineering teams on secure development practices",
        ],
        qualifications: [
            "6-10 years of experience in cybersecurity or information security",
            "Strong knowledge of network, application, and cloud security",
            "Experience with security frameworks and compliance standards",
            "Relevant certifications (CISSP, CEH, or similar) preferred",
            "Excellent incident response and problem-solving skills",
            "Bachelor's degree in Computer Science, Cybersecurity, or related field",
        ],
    },
];

export const getJobBySlug = (slug) => jobs.find((job) => job.slug === slug) || null;

export const getOtherJobs = (slug, limit = 3) =>
    jobs.filter((job) => job.slug !== slug).slice(0, limit);
